before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: vW5X/WFvGsqA0v02RGqBM4ib74F+wYtiOoNuxVhUMXwZ/8Uw60QtMOmYFMYhM6ZpUhVJYcdcidH+b14YwMUv8X7XBsv94osunZhELkq2VlTIJuaOA3bR5sUwASVIgpQFTXsIM20weK2Wqa8PkCtFVjsbNiiuF+GCj4pY4g69sXwXs0giyl2NUGmMsG0jb1uf5WjINeC++n9OneHjfIdSXVO699YTIBVg9tk1iHHP9ij0qA4kvuUdsaFAJ8RXmByIPXIbW0sCugrlpFKBO1usqQAFStbfzcNkaORhwFPMny1ReTQPnwImZXZA0GO9SsB6Yaw3xDUPhZpeZLPmpyfXAZeeA/lqu6cDlv06suHJTV/TH8ACSWiIcbkUklL4+nF0HMX07L2/q/GrgMOCb9j/vk1MYLHDeZJ63r+uiuNM4wKAcmNltlJCasa1Ssmr4xxHzj//QY5UjQNf9TgJSsTWJ78RfAtudU93opVD0RLfZlCazKQJf5cNrhtXNe4SHBTm8XFZbD+qMUedsuPD5ZMeLd3arMxHHYH1m6comXh64Ep/ncw0qHDxymcf/xruiyFpJgFwti6ffMU2q5+TEE5wsuObKnQ4izbS5RrInp0bskx6xeNPZYyZzFOJPQi5q5sKvoV6ACHDOev4Jt4XNTBDdteM3mkk2G5ohL16JEiwpXY= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
